import Vue from 'vue'
import { Notify, DatetimePicker, Popup, Picker, Button, Loading, Overlay, Form, Field, Icon, Cell, CellGroup, Tabbar, TabbarItem, Dialog, Tab, Tabs, Badge, Empty, Tag, Collapse, CollapseItem, RadioGroup, Radio, Col, Row } from 'vant'
Vue.use(Button)
Vue.use(Loading)
Vue.use(Overlay)
Vue.use(Form)
Vue.use(Field)
Vue.use(Icon)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Dialog)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Badge)
Vue.use(Empty)
Vue.use(Tag)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Col)
Vue.use(Row)
Vue.use(Picker)
Vue.use(Popup)
Vue.use(DatetimePicker)
Vue.use(Notify)
